### ISSUE TITLE
Unresolved node modules: @ef-carbon/url

### ISSUE THREAD

**Issue by carsonfarmer** [ef-carbon/fetch#5]
I get this when packaging for electron (via webpack). Running `yarn add --dev @ef-carbon/url` fixes the problem (not surprisingly).

**Comment by mattyclarkson** [comment]
`@ef-carbon/url` is a [peer dependency](https://github.com/ef-carbon/fetch/blob/master/package.json#L61-L63). You are required to install it yourself and determine which version of that package you would like to use.

**Comment by carsonfarmer** [comment]
Ah yup, apologies for the noise. I should have reported back here when I figured that out. Cheers!
